- package-lock.json
- package.json
- src/Backlink/Backlink.stories.tsx
- src/Backlink/Backlink.tsx
- src/Backlink/context.tsx
- src/Backlink/index.ts
- src/Backlink/styles.ts
- src/index.tsx
- src/theme/ThemeProvider.tsx
This PR adds backlink component.
> Add backlinks

- src/theme/ThemeProvider.tsx
- stories/guideStyles.ts
- stories/index.stories.tsx
> Add warnings to overrides

- src/styles/createTheme.ts
I want to merge this change as it fixes a styling issue related to scrolls in modals.
> change styles for DialogContent

- src/Savebar/ButtonTooltipDecorator.tsx
- src/Savebar/Savebar.stories.tsx
- src/Savebar/Savebar.tsx
- src/theme/createSaleorTheme/createSaleorTheme.ts
Needed for fulfillment page https://app.clickup.com/t/2549495/SALEOR-3860
In dashboard: https://github.com/mirumee/saleor-dashboard/pull/1248
> Add tooltips to savebar buttons

- src/SquareButton/SquareButton.stories.tsx
- src/SquareButton/SquareButton.tsx
This PR adds missing `disabled` state to `SquareButton`
> Add disabled state to SquareButton

- src/Backlink/Backlink.stories.tsx
- src/ConfirmButton/ConfirmButton.stories.tsx
- src/ConfirmButton/ConfirmButton.tsx
- src/ConfirmButton/styles.ts
- src/theme/createSaleorTheme/overrides/buttons.ts
This PR allows `ConfirmButton` to have variants.
Screenshots:
> Fix confirm button variants

- src/Alert/Alert.stories.tsx
- src/Alert/Alert.tsx
- src/Alert/AlertBase.tsx
- src/Alert/index.ts
This PR extracts `AlertBase` from `Alert` to allow customization.
Screenshots:
> Extract AlertBase from Alert

- src/Backlink/Backlink.stories.tsx
- src/LayoutButton/styles.ts
- src/Tooltip/Tooltip.tsx
- src/theme/createSaleorTheme/createSaleorTheme.ts
This PR improves `LayoutButton` hover and pressed states styles.
> Improve layout buttons

- src/icons/ImageIcon.tsx
- src/icons/index.ts
- stories/icons.stories.tsx
This PR adds image icon as well as story for all icons.
Screenshot:
> Add image icon

- src/theme/createSaleorTheme/createSaleorTheme.ts
This PR removes overflowX from MuiDialogContent.  This is change is required for Dashboard.
> Remove overflowX from MuiDialogContent

- src/Sidebar/Sidebar.tsx
It allows sidebar to scroll on short screens.
> Fix sidebar overflow Y issue

- src/theme/createSaleorTheme/overrides/inputs.ts
- stories/inputs.stories.tsx
This PR adds multiline text field input styles.
> Add textarea styles

- src/ActionBar/styles.ts
- src/Savebar/Savebar.tsx
- src/Savebar/styles.ts
This PR fixes button variants and tooltip placement in savebar.
> Update savebar buttons

- package.json
- scripts/esbuild.js
- src/theme/createSaleorTheme/types.ts
- src/utils/Decorator.tsx
- tsconfig.json
This PR fixes node builds (eg. jest tests).
> Fix module

- src/NavigationCard/NavigationCard.stories.tsx
- src/NavigationCard/NavigationCard.tsx
- src/NavigationCard/index.ts
- src/NavigationCard/styles.ts
- src/index.tsx
This PR adds navigation card component.
> Add navigation card

- src/theme/createSaleorTheme/overrides/inputs.ts
- stories/inputs.stories.tsx
This PR adds story for inputs with adornments and fixes input's disabled state.
> Improve input adornments when input is disabled

- src/LayoutButton/styles.ts
- src/Sidebar/ExpandButton.tsx
- src/Sidebar/MenuItem.tsx
- src/theme/createSaleorTheme/createSaleorTheme.tsx
- src/theme/createSaleorTheme/overrides/buttons.ts
This PR:
- fixes distance between icon and text in sidebar and changes expand icon
- fixes letter spacing value
- disables ripple on menu elements
> Minor fixes

- src/UserChipMenu/styles.ts
This PR fixes avatar image that was bigger than containing it button.
> Fix misplaced elements in responsive mode

- .storybook/main.js
- package-lock.json
- package.json
- src/utils/Decorator.tsx
> Add dark mode to Storybook

- src/Sidebar/MenuItem.tsx
- src/Sidebar/fixtures.ts
- src/Sidebar/types.ts
- src/SidebarDrawer/MenuItemBtn.tsx
- src/SidebarDrawer/SidebarDrawer.tsx
- src/SidebarDrawer/styles.ts
> Add subheader option to sidebar

- src/Button/Button.tsx
This PR wraps Button component in forward ref - it fixes issues with eg. popper.
> Wrap button in forward ref

- src/NavigationCard/NavigationCard.stories.tsx
- src/NavigationCard/NavigationCard.tsx
- src/NavigationCard/NavigationCardBase.tsx
- src/NavigationCard/index.ts
This PR allows NavigationCard's base component (card with hover effect) to be imported from macaw.
> Extract base component of navigation card

- src/Sidebar/MenuItem.tsx
- src/Sidebar/types.ts
- src/SidebarDrawer/MenuItemBtn.tsx
- src/SidebarDrawer/SidebarDrawer.tsx
Add possibility to create custom on-click handler in menu items. Will be used in https://github.com/saleor/saleor-dashboard/pull/1785.
> Update sidebar on-click handler

- src/Notification/Notification.stories.tsx
- src/Notification/Notification.tsx
- src/Notification/styles.ts
- src/Notification/types.ts
This PR:
+ adds error log to notifications as per task - https://app.clickup.com/t/220f11p 
+ moves action button to the right to match design
> Add error log to notifications

- src/ActionBar/ActionBar.tsx
- src/ActionBar/styles.ts
- src/Backlink/Backlink.tsx
- src/Savebar/Savebar.tsx
- src/theme/ThemeProvider.tsx
- src/theme/types.ts
It adds SSR support for components with portals and adds optional styles options to Savebar.
> SSR support for components with portals

- src/theme/createSaleorTheme/overrides/inputs.ts
Use regular font weight to enhance legibility of the multiline text and reduce similarity with buttons
> Font weight adjustment for inputs

- src/IconButton/styles.ts
- src/theme/themes.ts
- src/utils/guideStyles.ts
I want to merge this because the current disabled button color is green and it should be blue-ish to match enabled state
> Update disabled button cololor

- src/ActionBar/ActionBar.stories.tsx
- src/ActionBar/context.tsx
- src/IconButton/styles.ts
- src/utils/guideStyles.ts
I want to merge this because in the ActionBar example the component doesn't show up on the initial page render, it only shows when a theme is changed (or other action that causes React to re-render). The problem is that when ref for ActionBar is updated React doesn't re-render components in that context (refs don't cause rerenders).
> Force rerender in React for ActionBar example

- src/Backlink/Backlink.tsx
- src/Backlink/styles.ts
- src/LayoutButton/LayoutButton.tsx
I want to merge this because it adds support for custom Link component (like from react-router) in Backlink component
> Add support for custom Link component in Backlink

- src/Filter/FilterField/MultipleValueAutocompleteFilterField.tsx
- src/MultipleValueAutocomplete/MultipleValueAutocomplete.tsx
- src/Pagination/PaginationRowNumberSelect.tsx
I want to merge this because it fixes the formatting issues by running Prettier
> Fix formatting using Prettier

- src/Pill/Pill.stories.tsx
- src/Pill/Pill.tsx
- src/Pill/styles.ts
- src/theme/createSaleorTheme/types.ts
- src/theme/themes.ts
This PR adds new pill variant - `generic` and updates the styles to match new design
Preview: https://macaw-ui-git-fork-witoszekdev-new-pills-saleorcommerce.vercel.app/?path=/story/pill--default
Related dashboard PR: https://github.com/saleor/saleor-dashboard/pull/2234
> New pills design

- src/Pill/Pill.stories.tsx
- src/Pill/Pill.tsx
- src/Pill/styles.ts
I want to merge this so we can pass icons to Pill components (Chip from MUI)
> Allow passing icon to Pill component

- src/Avatar/Avatar.stories.tsx
- src/Avatar/Avatar.tsx
- src/Avatar/index.ts
- src/Avatar/styles.ts
- src/UserChipMenu/UserChipMenu.tsx
- src/index.tsx
I want to merge this because it adds Avatar from UserChipMenu as a separate component
> Add Avatar from UserChipMenu as a separate component

- src/Sidebar/MenuItem.tsx
Make menu items the same as the base buttons size
> Add consistent font size

- src/theme/Baseline.tsx
Adjust font size to be roughly equal to 15px to make information more compact while retaining comfortable font size
> Decrease base font size

- src/IconButton/IconButton.stories.tsx
- src/IconButton/IconButton.tsx
- src/theme/createSaleorTheme/createSaleorTheme.tsx
- src/theme/createSaleorTheme/overrides/tables.ts
- src/theme/createSaleorTheme/types.ts
- src/theme/themes.ts
This PR adds border to cards and changes default background color.
> Add border to cards

- src/PageTabs/PageTab.stories.tsx
- src/PageTabs/styles.ts
This PR updates Page Tabs to new design and improves docs.
> Update Page Tabs to new design

- src/Accordion/Accordion.tsx
- src/icons/24x24/ChevronIcon.tsx
Fixes https://github.com/saleor/saleor-dashboard/issues/2720
> Add epxand-icon test id for ChevroneIcon

- src/Alert/Alert.tsx
- src/Alert/AlertBase.tsx
- src/DialogHeader/DialogHeader.tsx
- src/Notification/Notification.tsx
- src/Pagination/PaginationActions.tsx
- src/Savebar/Savebar.tsx
- src/Sidebar/MenuItem.tsx
- src/SidebarDrawer/MenuItemBtn.tsx
- src/UserChipMenu/UserChipMenu.tsx
> Standardize test locators to data-test-id

- .storybook/main.cjs
- package.json
- pnpm-lock.yaml
* I've added types so consumers on MacawUI have proper types for `macaw-ui` and `macaw-ui/next`
* Applied fixes for pkg version
* Make releases pre release as default
> Fixes in pkg.json & storybook with aliases

- package.json
- pnpm-lock.yaml
- src/components/List/Item.stories.tsx
- src/components/List/Item.tsx
- src/components/List/List.stories.tsx
- src/components/List/List.tsx
- src/components/List/index.ts
- src/components/Text/Text.tsx
- src/components/index.ts
- src/theme/contract.css.ts
- src/theme/defaultLight.css.ts
- src/theme/reset.css.ts
- src/theme/sprinkles.css.ts
- src/utils/utils.test.ts
- vite.config.ts
I've added `List` & `List.Item` components
* `disabled=true`
* `default`
Other components like `List.ItemGroup` will be created in other PR.
> List item implementation

- src/theme/contract.css.ts
- src/theme/defaultLight.css.ts
Adds `space-0` to scale and sets CSS variable
> Add space-0 to scale

- src/components/List/Item.tsx
- src/theme/sprinkles.css.ts
* Add proper colors to list
* Add `minHeight` & `minWidth` to sprinkles
> Small adjustments to list and sprinkles

- src/components/index.ts
- src/theme/sprinkles.css.ts
> Add missing dropdown export

- package.json
- pnpm-lock.yaml
- src/components/Drawer/Content.css.ts
- src/components/Drawer/Content.tsx
- src/components/Drawer/Drawer.stories.tsx
- src/components/Drawer/Root.tsx
- src/components/Drawer/Trigger.tsx
- src/components/Drawer/common.css.ts
- src/components/Drawer/index.ts
- src/components/List/ItemGroup/Trigger.tsx
- src/components/index.ts
- src/theme/sprinkles.css.ts
* Small additions to sprinkles
> Add Drawer

- src/components/Avatar/Store/Store.tsx
- src/components/Avatar/User/User.tsx
- src/components/Drawer/Content.tsx
- src/components/Icons/SVGWrapper/SVGWrapper.tsx
- src/components/List/Divider.tsx
- src/components/List/Item.tsx
- src/components/List/ItemGroup/Root.tsx
- src/components/List/ItemGroup/Trigger.tsx
- src/components/List/List.tsx
- src/components/Text/Text.tsx
- src/components/types.ts
- src/theme/sprinkles.css.ts
This PR allows passing arbitrary `data-*` attributes to MacawUI components.
> Add data-* attributes

- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
I want to merge this change because it adds native HTML attributes to Button component.
> Fix button HTML attributes

- src/components/Button/Button.css.ts
- src/components/Button/Button.stories.tsx
- src/theme/sprinkles.css.ts
This PR adds shadows to buttons.
> Add box shadows to buttons

- src/components/Icons/InfoIcon.tsx
- src/components/Icons/index.ts
> Add info icon

- src/components/Avatar/common.css.ts
- src/components/Chip/Chip.css.ts
- src/components/Chip/Chip.stories.tsx
- src/components/Chip/Chip.tsx
- src/components/Chip/index.ts
- src/components/index.ts
> Implement chips

- src/components/Icons/WarningIcon.tsx
- src/components/Icons/index.ts
> Add warning icon

- src/components/Box/Box.stories.tsx
- src/theme/sprinkles.css.ts
* zIndex
* Ability to create layout based on grid columns & rows
> feat: add zindex and layout

- src/components/List/ItemGroup/Trigger.tsx
- src/theme/sprinkles.css.ts
Fix for https://github.com/saleor/saleor-dashboard/issues/3203
> List collapse trigger change

- legacy/src/theme/Baseline.tsx
- legacy/src/theme/createSaleorTheme/createSaleorTheme.tsx
- src/theme/fonts.css.ts
* I've removed CDN for Inter font - right now we are going to use Inter variable from the MacawUI build.
Fixes #268
> Remove CDN for font

- src/components/index.ts
This PR exports checkbox component.
> Export checkbox

- src/theme/context.tsx
- src/theme/themes/index.ts
It returns all selected theme values so you don't need to do it manually in e.g dashboard 😄
> Return all selected theme values from theme

- src/components/Icons/ViewTableIcon.tsx
- src/components/Icons/ViewWideTilesIcon.tsx
- src/components/Icons/index.ts
- src/components/Switch/Item.tsx
- src/components/Switch/Switch.css.ts
- src/components/Switch/Switch.stories.tsx
- src/components/Switch/Switch.tsx
- src/components/Switch/index.ts
- src/components/index.ts
This PR implements basic switch component. Hover states are going to be added very soon when designs are available.
> Add switch component

- src/theme/sprinkles.css.ts
This PR adds grid auto flow property to sprinkles.
> Add auto flow propery to sprinkles

- src/components/Switch/Item.tsx
- src/components/Switch/Switch.css.ts
- src/components/Switch/Switch.stories.tsx
Closes #293.
This PR adds support for disabled states, improves colors & spacings.
<p float="middle">
</p>
> Improve switch component

- package.json
This PR bumps release version (normally it is done by release-it tool, but a problem ocurred during release process)
> Release 0.8.0-pre.50

- src/components/Input/InputWrapper.tsx
Currently, the dashboard input value is not changing when the response comes back from API. It means that once the value is set to e.g empty string (as a fallback) it stays as an empty string even when UI has the proper value from API. This PR fixes that 😄
> Fix input value not changing

- package.json
- pnpm-lock.yaml
- src/components/Toggle/Toggle.css.ts
- src/components/Toggle/Toggle.stories.tsx
- src/components/Toggle/Toggle.tsx
- src/components/Toggle/index.ts
- src/components/index.ts
- src/theme/contract.css.ts
- src/theme/themes/common.ts
This PR implements Toggle component.
**known bug**: active state is not triggered on toggle when clicking on label multiple times (chrome only)
> Implement toggle

- src/components/Expression/AutosizeInput/useTextMetrics.ts
- src/components/RadioGroup/Group.tsx
- src/components/RadioGroup/RadioGroup.stories.tsx
- src/theme/sprinkles.css.ts
* Swapped `defaultValue` to `value` for RadioGroup - it should work properly as a controlled component
* Added `baseline` to align item prop
* Moved canvas to hooks - it was causing Next.js SSR to break
> Fix radio group and support for SSR

- package-lock.json
- src/components/DropdownButton/DropdownButton.css.ts
- src/components/DropdownButton/DropdownButton.stories.tsx
- src/components/DropdownButton/DropdownButton.tsx
> Dropdown button variant 'text'

- src/components/Text/Text.stories.tsx
- src/theme/stories/borders.stories.tsx
- src/theme/stories/colors.stories.tsx
- src/theme/stories/shadows.stories.tsx
- src/theme/stories/space.stories.tsx
I added this change so Design and Product teams can easily check all current components/tokens in MacawUI
> Add additional stories to storybook

- src/components/Avatar/Store/Store.tsx
- src/components/Avatar/User/User.tsx
- src/components/Avatar/index.ts
- src/components/Box/Box.tsx
- src/components/Button/Button.tsx
- src/components/Chip/Chip.tsx
- src/components/DropdownButton/DropdownButton.tsx
- src/components/Input/Input.tsx
- src/components/SearchInput/SearchInput.tsx
- src/components/Text/Text.stories.tsx
- src/components/Text/Text.tsx
This PR applies types from Box to all current components
> Apply types from Box to components

- package.json
- pnpm-lock.yaml
- src/components/Tooltip/Arrow.tsx
- src/components/Tooltip/Content.tsx
- src/components/Tooltip/ContentHeading.tsx
- src/components/Tooltip/Root.tsx
- src/components/Tooltip/Tooltip.css.ts
- src/components/Tooltip/Tooltip.stories.tsx
- src/components/Tooltip/Trigger.tsx
- src/components/Tooltip/index.ts
- src/components/index.ts
* Added `Tooltip` component to MacawUI
> Add Tooltip component

- src/components/Input/Input.tsx
This PR adds more input types:
* `url`
* `password`
* `email`
> Add more input types

- src/components/Checkbox/CheckedIcon.tsx
- src/components/Checkbox/IndeterminateIcon.tsx
This PR fixes missing refs for Checkbox icons.
> Add missing refs to Checkbox

- src/components/Button/Button.css.ts
- src/components/Checkbox/Checkbox.css.ts
- src/components/DropdownButton/DropdownButton.css.ts
- src/components/List/Item.tsx
- src/components/Switch/Switch.css.ts
- src/components/Toggle/Toggle.css.ts
It fixes: #278 and removes not needed `pointer-events: none`
> fix: remove pointer events: none

- src/components/DropdownButton/DropdownButton.stories.tsx
- src/components/Expression/Expression.stories.tsx
- src/components/Expression/OperandRange.tsx
new stories for:
- ButtonDropdown
- Expression
> docs: new stories for button dropdown and expression

- src/components/RadioGroup/RadioGroup.stories.tsx
- src/components/SearchInput/SearchInput.stories.tsx
- src/components/Switch/Switch.stories.tsx
New stories for:
- RadioGroup
- SearchInput
- Swtich
> docs: new stories for radio group, search, swtich

- src/components/Text/Text.stories.tsx
- src/components/Toggle/Toggle.stories.tsx
- src/components/Tooltip/Tooltip.stories.tsx
New stories for:
- Text
- Toggle
- Tooltip
> docs: new stories for text, toogle, tooltip

- src/components/Input/Input.stories.tsx
- src/components/List/List.stories.tsx
- src/components/Popover/Popover.stories.tsx
New stories for:
- List
- Input
- Popover
> docs: new stories for input list and popover

- .github/pull_request_template.md
> chore: add storybook story requirement to the pull request template

- src/theme/docs/CustomStyling.mdx
- src/theme/docs/Instalation.mdx
- src/theme/docs/UsingTokens.mdx
> docs: getting started section in our documentation

- README.md
- package.json
I want to merge this change because it adds watch mode (useful for cases when you are linking macaw-ui from the dashboard)
> chore: add watch mode

- .storybook/components/BorderRadius.tsx
- .storybook/components/Colors.tsx
- .storybook/components/Shadow.tsx
- .storybook/components/Spacings.tsx
Set constant captions to not be influenced by theme change.
> docs: set constant captions

- src/components/Checkbox/Checkbox.css.ts
- src/components/Checkbox/Checkbox.tsx
I want to merge this change because it fixes missing cursor pointer on checkboxes.
This PR closes #415.
> fix: missing cursor pointer on checkbox

- .github/workflows/main.yml
- package.json
- pnpm-lock.yaml
I want to merge this change because it adds [Chromatic](https://www.chromatic.com/) support for MacawUI.
> build: add chromatic on pull request

- package.json
- src/components/Combobox/Combobox.tsx
- src/components/Combobox/ComboboxWrapper.tsx
- src/components/Multiselect/Adornment.tsx
- src/components/Multiselect/Multiselect.css.ts
- src/components/Multiselect/Multiselect.stories.tsx
- src/components/Multiselect/Multiselect.tsx
- src/components/Multiselect/MultiselectWrapper.tsx
- src/components/Multiselect/index.ts
- src/components/Multiselect/useMultiselectEvents.tsx
- src/components/index.ts
- src/theme/sprinkles.css.ts
I want to merge this change because it adds `<Multiselect/>` component with Combobox.
This PR closes #350
> feat: multiselection component

- src/components/Button/Button.css.ts
- src/components/Button/Button.stories.tsx
I want to merge this change because it's adding an error variant to the button component
> feat: add button error variant

- src/components/BaseSelect/BaseSelect.css.ts
- src/components/Button/Button.css.ts
- src/components/Chip/Chip.css.ts
- src/components/Chip/Chip.stories.tsx
- src/components/Chip/Chip.tsx
- src/components/Combobox/Combobox.tsx
- src/components/Combobox/useComboboxEvents.tsx
- src/theme/contract.css.ts
- src/theme/sprinkles.css.ts
- src/theme/themes/common.ts
> fix: chip styles

- .husky/pre-commit
- .husky/pre-push
- src/components/Input/Input.tsx
- src/components/Select/Select.tsx
- src/components/Text/Text.tsx
- src/theme/sprinkles.css.ts
> fix: fixes to Select, Input, Text and husky

- src/components/Accordion/Accordion.stories.tsx
- src/components/Accordion/Item/Trigger.tsx
- src/components/Accordion/Item/TriggerButton.tsx
- src/components/Accordion/Item/index.ts
- src/components/Accordion/index.ts
I want to merge this change because it closes https://github.com/saleor/saleor-dashboard/issues/3711
> feat: decouple trigger button from accordion

- src/components/Icons/ExternalLinkIcon.tsx
- src/components/Icons/index.ts
> feat: add external link icon

- .github/ISSUE_TEMPLATE/rfc.yml
I want to merge this change because it adds new RFC template
> chore: add rfc template

- src/components/Popover/Root.tsx
I want to merge this change because it enables using popover as a modal.
> feat: add modal feature to popover

- .github/CONTRIBUTING.md
> docs: remove not needed parts from contribution guide

- src/components/ExperimentalFilters/EventEmitter.ts
- src/components/ExperimentalFilters/ExperimentalFilters.stories.tsx
- src/components/ExperimentalFilters/ExperimentalFilters.tsx
- src/components/ExperimentalFilters/index.ts
- src/components/ExperimentalFilters/useEvents.tsx
- src/components/index.ts
I want to merge this change because it adds the `_ExperimentalFilters` component needed for Product List filters.
> feat: experimental filters

- src/components/ExperimentalFilters/ExperimentalFilters.stories.tsx
- src/components/ExperimentalFilters/ExperimentalFilters.tsx
> fix: add disabled state to experimental filters

- src/components/ExperimentalFilters/EventEmitter.ts
- src/components/ExperimentalFilters/ExperimentalFilters.stories.tsx
- src/components/ExperimentalFilters/ExperimentalFilters.tsx
- src/components/ExperimentalFilters/context.ts
- src/components/ExperimentalFilters/index.ts
> feat: add footer with actions to experimental filters

- src/components/ExperimentalFilters/ExperimentalFilters.tsx
- src/components/ExperimentalFilters/index.ts
> fix: props imports for ExperimentalFilters

- .github/workflows/chromatic.yml
- .github/workflows/main.yml
- .github/workflows/pull_request.yml
- package.json
- src/components/Combobox/Static/StaticCombobox.stories.tsx
- src/components/Multiselect/Static/Multiselect.stories.tsx
I want to merge this change because this pins the `pnpm` version. Workflows will use version defined in package.json.
> chore: pin pnpm version

- src/components/ExperimentalFilters/EventEmitter.ts
- src/components/ExperimentalFilters/RightOperator.tsx
- src/components/ExperimentalFilters/Row.tsx
I want to merge this change because it adds date input to the experimental filter
> feat: add date input to experimental filter

- src/components/ExperimentalFilters/EventEmitter.ts
- src/components/ExperimentalFilters/RightOperator.tsx
- src/components/Input/Input.stories.tsx
- src/components/Input/Input.tsx
- src/components/Input/InputWrapper.tsx
- src/components/Input/helpers.ts
I want to merge this change because it adds date time input to MacawUI.
> feat: add date time input

- src/components/ExperimentalFilters/ExperimentalFilters.stories.tsx
- src/components/ExperimentalFilters/Filters.tsx
- src/components/ExperimentalFilters/Footer.tsx
- src/components/ExperimentalFilters/NoValue.tsx
- src/components/ExperimentalFilters/Root.tsx
- src/components/ExperimentalFilters/Row.tsx
- src/components/ExperimentalFilters/context.ts
- src/components/ExperimentalFilters/index.ts
I want to merge this change because it:
* adds an empty state for filters
* adjusts loading state
* adjusts spacing
> feat: add empty state for experimental filters and spacing

- src/components/ExperimentalFilters/ExperimentalFilters.stories.tsx
- src/components/ExperimentalFilters/RightOperator.tsx
- src/components/ExperimentalFilters/operators.ts
- src/components/ExperimentalFilters/types.ts
I want to merge this change because it adds ranges for date/datetime
> feat: experimental filters - add ranges

- src/components/ExperimentalFilters/EventEmitter.ts
- src/components/ExperimentalFilters/RangeInputWrapper.tsx
- src/components/ExperimentalFilters/RightOperator.tsx
- src/components/ExperimentalFilters/types.ts
- src/components/RangeInput/RangeInput.stories.tsx
- src/components/RangeInput/RangeInput.tsx
- src/components/RangeInput/index.ts
- src/components/index.ts
I want to merge this change because it adds `RangeInput`
> feat: range input

- .eslintrc.cjs
- src/components/ExperimentalFilters/ExperimentalFilters.stories.tsx
- src/components/ExperimentalFilters/RightOperator.tsx
I want to merge this change because this PR fixes a couple of bugs:
* `helperText` was not properly passed to ranges
* fixed error in the dashboard when default disabled input was changing from uncontrolled to controlled input
> fix: experimental filters helper text and empty input bugs

- src/components/BaseInput/BaseInput.css.ts
- src/components/Combobox/Common/ComboboxWrapper.tsx
- src/components/Multiselect/Common/MultiselectWrapper.tsx
- src/components/Select/SelectWrapper.tsx
I want to merge this change because it fixes wrong cursor for selects
> fix: wrong cursor for selects

- package.json
I want to merge this change because it fixes paths to generated `d.ts` files
> fix: paths to generated d.ts files

- src/components/Modal/Close.tsx
- src/components/Modal/Content.css.ts
- src/components/Modal/Content.tsx
- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Root.tsx
- src/components/Modal/Trigger.tsx
- src/components/Modal/index.ts
I want to merge this change because it adds `Modal` component
> feat: modal component

- package.json
- pnpm-lock.yaml
I want to merge this change because it fixes broken dependencies
> fix: revert broken deps

- package.json
> chore: fix wrong cmd for visualizer

- src/components/Textarea/Textarea.stories.tsx
- src/components/Textarea/Textarea.tsx
- src/components/Textarea/TextareaWrapper.tsx
- src/components/Textarea/index.ts
- src/components/index.ts
This PR closes https://github.com/saleor/macaw-ui/issues/325
> feat: textarea component

- src/components/BaseSelect/helpers.ts
- src/components/Combobox/Dynamic/DynamicCombobox.tsx
- src/components/Multiselect/Dynamic/DynamicMultiselect.tsx
> feat: improve loading state on combobox and multiselect

- src/components/BaseInput/BaseInput.css.ts
- src/components/Input/Input.stories.tsx
I want to merge this change because it changes default styles for non-active input
This PR closes #536
> fix: default styles for non-active input

- src/components/BaseSelect/helpers.ts
- src/components/Combobox/Dynamic/DynamicCombobox.stories.tsx
- src/components/Combobox/Dynamic/DynamicCombobox.tsx
- src/components/Multiselect/Dynamic/DynamicMultiselect.tsx
> fix: show loading state in dynamic combobox and multiselect

- src/components/Combobox/Common/useCombobox.tsx
> fix:  passing value to onInputValueChange in useCombobox hook

- src/components/BaseInput/BaseInput.css.ts
- src/theme/themes/defaultDark.ts
- src/theme/themes/defaultLight.ts
I want to merge this change because it fixes helper text spacing and border color for inputs.
> fix: helper text spacing and border color

- package.json
- src/components/BaseSelect/BaseSelect.css.ts
- src/components/BaseSelect/helpers.ts
- src/components/Combobox/Dynamic/DynamicCombobox.tsx
- src/components/Combobox/Static/Combobox.tsx
- src/components/Multiselect/Dynamic/DynamicMultiselect.tsx
- src/components/Multiselect/Static/Multiselect.tsx
- src/components/Select/Select.tsx
I want to merge this change because it changes dropdown sizes for small selects, comboboxes and multiselects.
> feat: change sizes for dropdown in selects

- src/components/BaseSelect/BaseSelect.css.ts
I want to merge this change because it fixes dropdown for Select, Combobox & Multiselect.
| ![CleanShot 2023-09-04 at 12 27 55@2x](https://github.com/saleor/macaw-ui/assets/9116238/67a8920f-cb94-46ae-b07d-af293139d0bd) | <img width="324" alt="image" src="https://github.com/saleor/macaw-ui/assets/9116238/b355719a-156c-4f49-8666-ae89dcc8db75"> |
> fix: select dropdowns style

- src/components/BaseInput/BaseInput.css.ts
I want to merge this change because this PR changes border colors on hover for inputs
> fix: border colors on hover for inputs

- src/components/Combobox/Dynamic/DynamicCombobox.stories.tsx
- src/components/Combobox/Dynamic/DynamicCombobox.tsx
- src/components/Multiselect/Dynamic/DynamicMultiselect.stories.tsx
- src/components/Multiselect/Dynamic/DynamicMultiselect.tsx
- src/hooks/useInfnityScroll.ts
I want to merge this change because it adds infnifty scroll feature for both dynamic inputs
> feat: infinity scroll for dynami multiselect and combobox

- src/components/Multiselect/Dynamic/DynamicMultiselect.tsx
- src/components/Multiselect/Static/Multiselect.tsx
> feat: add data-test-id to multiselect selected options

- package.json
> chore: fix release

- package.json
I want to merge this change because it bumps version in package.json
> chore: fix release 1.0.0-pre.5

- src/components/Modal/Content.tsx
> feat: allow the user to disable autofocus in modal

- adr/template.md
> chore: introduce adr template

- src/components/Input/InputWrapper.tsx
- src/components/Input/helpers.test.ts
- src/components/Input/helpers.ts
- src/components/Input/types.ts
I want to merge this change because it fix handling 0 value, as it's falsy and label doesn't go up
> fix: handling 0 vales in input component

- package.json
> chore: fix release 1.0.0-pre.8

- src/components/Switch/Switch.tsx
> fix: handle controlled state in Switch component

- adr/00001-goal-and-users.md
> docs: adr 00001 Goal and users of macaw UI

- adr/00002-theming-by-users.md
> docs: adr 00002 Theming by users

- adr/00003-color-tokens-spec.md
> docs: adr 00003 Color tokens specification 

- src/components/Icons/EnvironmentIcon.tsx
> fix: stroke width for env icon

- src/components/Popover/Content.tsx
I want to merge this change because it adds option that allow disabling autofocus for popover - we need that in Saleor Cloud.
> feat: add option to disable autofocus for popover

- src/components/BaseSelect/NoOptions/NoOptions.tsx
- src/components/BaseSelect/NoOptions/helpers.ts
- src/components/BaseSelect/NoOptions/index.ts
> fix: dropdown no options component

- src/components/BaseSelect/NoOptions/NoOptions.tsx
> feat: pass text props to NoOptions component

- src/theme/contract.css.ts
- src/theme/themes/defaultDark.ts
- src/theme/themes/defaultLight.ts
| ![CleanShot 2024-01-23 at 15 06 39@2x](https://github.com/saleor/macaw-ui/assets/9116238/aad1e2f2-4ad8-43e7-9c6d-9e03015667f6) | ![CleanShot 2024-01-23 at 15 05 26@2x](https://github.com/saleor/macaw-ui/assets/9116238/bde3b6de-4cc0-482b-a781-361bf82ac9f0) |
> fix: wrong warning colors

- .github/dependabot.yml
> Change dependabot schedule to monthly

- .github/workflows/prepare-release.yml
I want to merge this change because we need to run tests on release branch. We have the same problem in app-sdk: https://github.com/saleor/app-sdk/blob/main/.github/workflows/prepare-release.yml
> Update prepare release workflow

- .changeset/ninety-pens-confess.md
- package.json
> Fix empty build on npm

- .changeset/hungry-ghosts-help.md
- README.md
- package.json
- src/components/Tooltip/Content.tsx
- src/components/Tooltip/Tooltip.css.ts
- src/components/Tooltip/Tooltip.stories.tsx
> fix: showing tooltip content when no children

- .changeset/silent-spies-laugh.md
- src/components/Select/Select.stories.tsx
- src/components/Select/Select.tsx
> Add adornments to Select input

- .github/workflows/chromatic.yml
- .github/workflows/dev-release.yml
- .github/workflows/main.yml
- .github/workflows/prepare-release.yml
- package.json
- pnpm-lock.yaml
> Update pnpm to 9.7.1

- .changeset/five-bats-joke.md
- src/components/Checkbox/Checkbox.css.ts
- src/theme/contract.css.ts
- src/theme/themes/defaultDark.ts
- src/theme/themes/defaultLight.ts
> Improve checkbox colours on focus and active states

- .changeset/early-planets-do.md
- src/components/Combobox/Common/ComboboxWrapper.tsx
- src/components/Combobox/Static/StaticCombobox.stories.tsx
- src/components/Select/Select.stories.tsx
- src/components/Select/Select.tsx
- src/components/Select/SelectWrapper.tsx
I want to merge this change because it makes select label full width and fix ellipses 
> Select label width adjustment

- .changeset/friendly-guests-itch.md
- .github/workflows/check-licenses.yaml
- LICENSE
This adds a workflow that checks our repository does not use non-CC-BY-4.0 compatible licenses.
The workflow reviews each pull requests against given rules, and sends a summary.
This also adds a LICENSE file which was missing.
> Add workflow to check licenses

- .changeset/fluffy-poets-confess.md
- src/components/Backdrop/Backdrop.tsx
- src/components/Icons/SVGWrapper/createSVGWrapper.tsx
- src/components/Paragraph/Paragraph.tsx
- src/components/RangeInput/RangeInput.tsx
- src/components/Skeleton/Skeleton.tsx
- src/components/Spinner/Spinner.tsx
I want to merge this change because it adds `data-macaw-ui-component` attribute to all components in Macaw.
> Add missing data-macaw-ui-component

- .changeset/nice-nails-grin.md
- src/components/Accordion/Accordion.stories.tsx
- src/components/Accordion/Root.tsx
> Accordion root `type: 'multiple'`

- .changeset/hungry-hounds-call.md
- src/components/Combobox/Common/useCombobox.tsx
- src/components/Combobox/Dynamic/DynamicCombobox.tsx
- src/components/Combobox/Static/Combobox.tsx
- src/components/List/List.tsx
- src/components/Multiselect/Common/useMultiselect.tsx
- src/components/Multiselect/Dynamic/DynamicMultiselect.tsx
- src/components/Multiselect/Static/Multiselect.tsx
- src/components/Select/Select.tsx
- src/components/Select/SelectWrapper.tsx
- src/hooks/useFloating.ts
This reverts commit 84e01e3308d56547360010243c8f76a2646939e7.
> Revert floating-ui changes 
