src/ResponsiveTable/ResponsiveTable.tsx
src/ResponsiveTable/index.ts
src/ResponsiveTable/styles.ts
src/index.tsx
src/theme/createSaleorTheme/overrides/tables.ts
stories/guideStyles.ts
stories/index.stories.tsx
stories/tables.stories.tsx

This PR adds quick table usage demonstration and introduces `ResponsiveTable` component as well as changes the way `TableCell` is sized.
Note: built on top of #22

Add quick table guide

---

src/theme/createSaleorTheme/overrides/inputs.ts

Removes unnecessary zIndex values. MaterialUI should already handle the correct z-index positioning. The changes are tested in this PR: https://github.com/mirumee/saleor-dashboard/pull/1292

Remove hardcoded zIndex values

---

src/theme/createSaleorTheme/createSaleorTheme.ts

It seems https://github.com/saleor/macaw-ui/pull/54 did not resolve issue in all places.

Fix dialog overflows

---

src/theme/createSaleorTheme/overrides/buttons.ts
src/theme/createSaleorTheme/overrides/index.ts
src/theme/createSaleorTheme/overrides/inputs.ts
src/theme/createSaleorTheme/overrides/tables.ts
src/theme/createSaleorTheme/shadows.ts
src/theme/createSaleorTheme/types.ts

This PR fixes deep imports within library.

Fix deep imports

---

src/Button/Button.tsx
src/theme/createSaleorTheme/overrides/buttons.ts
src/theme/createSaleorTheme/types.ts
src/theme/themes.ts
stories/buttons.stories.tsx

This PR adds `color="text"` prop to Button component.
Screenshot:

Add text color button variants

---

src/Tooltip/Tooltip.tsx

I want to merge this change because it adds `disabled` prop to Tooltip component.
Often Tooltip is rendered conditionally:
```
condition
? <Tooltip><Element /></Tooltip>
: <Element />
```
This is difficult to read when `<Element />` has a lot of props. Adding `disabled` prop will result in easier syntax:
```
<Tooltip disabled={condition}>
<Element />
</Tooltip>
```

Add disabled prop to tooltip

---

src/theme/createSaleorTheme/overrides/controls.ts
stories/controls.stories.tsx

This PR fixes switch placement when used in `<FormControlLabel control={Switch} />`, resulting in occasional clipping.

Fix switch placement in FormControlLabel

---

src/ActionBar/ActionBar.tsx
src/ActionBar/context.tsx
src/ActionBar/styles.ts
src/Savebar/Savebar.tsx

This PR removes savebar's ability to dock at the bottom of the page (not screen) if nothing has changed in form.

Do not dock savebar if not scrolled to bottom

---

src/IconButton/IconButton.tsx
src/IconButton/styles.ts
src/utils/guideStyles.ts
stories/buttons.stories.tsx

IconButtons didn't apply correct styling when `state` prop was provided. This PR fixes the problem.

Fix IconButton state prop

---

src/IconButton/styles.ts
src/Sidebar/MenuItem.tsx
src/Sidebar/Sidebar.tsx
src/Sidebar/types.ts
src/Sidebar/utils.ts
src/SidebarDrawer/MenuItemBtn.tsx
src/SidebarDrawer/SidebarDrawer.tsx
src/utils/guideStyles.ts

I want to merge this change in order to use custom Link component (for example from react-router) in Sidebar and SidebarDrawer so that we can open links from `Sidebar` and Logo inside `Sidebar` in new tab using Cmd+click

Change Sidebar and SidebarDrawer to allow custom Link component

---

src/Autocomplete/Autocomplete.tsx
src/IconButton/IconButton.tsx
src/LayoutButton/LayoutButton.tsx
src/SwitchSelector/SwitchSelector.stories.tsx
src/SwitchSelector/SwitchSelector.tsx
src/SwitchSelector/SwitchSelectorButton.tsx

I want to merge this because it adds support for polymorphic components in IconButton (ex. Link from react-router).
It also adds types for passing href prop to IconButton (supported by underlying IconButton and BaseButton from MUI) and fixes issues with Backlink not passing down component prop.

Add support for router link and href in IconButton, fix Backlink

---

.eslintrc.js

I want to merge this to warn developers about leftover console.log's in the codebase (allowed in Stories)

Add ESLint rule `no-console` to warn about leftover console.log's

---

src/Autocomplete/Autocomplete.tsx
src/Autocomplete/styles.ts
src/MultipleValueAutocomplete/styles.ts
src/consts.ts

This PR fixes:
1. warning that ref is not properly mounted (it's a common problem with downshift and portals)
2. z-index in popper, because autocomplete components were unusable inside dialogs

Fix ref errors and z index

---

src/CircleIndicator/CircleIndicator.tsx
src/Indicator/index.ts
src/Indicator/styles.ts
src/Tooltip/TooltipMountWrapper.tsx
src/Tooltip/index.ts
src/Tooltip/styles.ts
src/index.tsx

I want to merge this because it fixes issues with new components:
**Indicator**
- Mark `CircleIndicator` as deprecated (superseded by `IndicatorCircle`)
- Add missing name in makeStyles to generate more readable classNames
- Add missing exports in `src/index.tsx` for Indicator folder
- Add missing exports in `/Indicator/index.ts` to export all Indicator components
- Fix absolute positioning of SVGs used inside flex container
**Tooltip**
- Add TooltipMountWrapper component for using Indicator without `<button>`

Fix issues with Tooltip and Indicator

---

src/Pagination/Pagination.tsx
src/Pagination/PaginationActions.tsx

I want to merge this because it adds support for custom Link component (ex. from react-router) into Pagination buttons. It also adds more strict TS types for type checking props passed into Pagination buttons

Add support for Link in Pagination

---

src/Tooltip/Tooltip.tsx

I want to merge this change because it moves early return clause behind hook calls in Tooltip component. This fixes inconsistent amount of hook calls when `disabled` prop changes.

Fix early return in Tooltip component

---

src/ResponsiveTable/ResponsiveTable.tsx
src/ResponsiveTable/styles.ts

I want to merge this, because it adds an option to customize breakpoint in ResponsiveTable. It also allows consumers of library to pass arbitrary props to `<Table>` and `<div>` components
Related dashboard PR: https://github.com/saleor/saleor-dashboard/pull/2234

Customize breakpoint in ResponsiveTable

---

src/Notification/Notification.tsx

Adds `data-test-id` to notification elements so cypress can target them better in tests.

Add data-test-ids to notifications

---

src/components/Icons/SVGWrapper/SVGWrapper.tsx
src/components/Icons/SVGWrapper/createSVGWrapper.tsx
src/components/Icons/icons.stories.tsx
src/components/List/Item.tsx
src/components/List/ItemGroup/Trigger.tsx
src/components/List/ItemGroup/styles.css.ts
src/components/List/List.stories.tsx

Add colors to List.ItemGroup.Trigger

---

src/components/Button/Button.stories.tsx
src/components/Icons/SVGWrapper/SVGWrapper.css.ts
src/components/Icons/icons.stories.tsx
src/components/List/ItemGroup/Trigger.tsx

* I've removed an `xsmall` variant from the icon as small icon currently is 16x16
* Added ability to pass size to `ListItemGroup.Trigger`

Pass proper chevron icon size

---

src/theme/sprinkles.css.ts

We have following use case in the dashboard: `<a>` tags are used as wrappers which allow right clicking and/or opening stuff in new tabs. Using `display: contents` on them makes them not interfere with flexbox styling or child selectors.

Add display: contents to sprinkles

---

src/components/Input/Input.css.ts
src/components/Input/Input.stories.tsx
src/components/Input/Input.tsx
src/components/Input/InputWrapper.tsx
src/components/Input/index.ts
src/components/index.ts
src/theme/sprinkles.css.ts

Ref: https://github.com/saleor/macaw-ui/issues/232 (partially closes)

Inputs implementation

---

src/components/Text/Text.css.ts
src/components/Text/Text.tsx
src/theme/sprinkles.css.ts

This PR adds `ellipsis` parameter to Text component in 3 variants:
- `true` with `whitespace: nowrap`, for single-line overflowing spans (working in containers with set width)
- `multiline` without nowrap, for multi-line overflowing spans (working in containers with set width & height)
- `false` which is default and current behaviour.

Add ellipsis to Text

---

src/theme/sprinkles.css.ts

This PR adds css properties useful for resizing thumbnails, e.g: 
Before:
After:

Add aspect ratio & object-fit to sprinkles

---

src/components/Icons/SVGWrapper/SVGWrapper.css.ts

This PR adds `fill` variant for icon size which allows for variable-sized icons.

Add fill size variant to icon components

---

src/theme/sprinkles.css.ts

This PR adds `opacity` css property to sprinkles with the following values: `0` | `0.2` | `0.4` | `0.6` | `0.8` | `1`

Add opacity to sprinkles

---

src/components/Box/Box.tsx
src/components/List/ItemGroup/Trigger.tsx
src/components/List/List.stories.tsx

It fixes `PropsWithBox` types so properties passed into the `PropsWithBox` generic will override those from `Box`. 
Take `ItemGroupTriggerProps` where the `size` property is coming from both custom code `size?: "small" | "medium" | "large"` and from `Box` where `size: number | undefined`. Before the fix size was resolved as `number` and after the fix is resolved as `"small" | "medium" | "large"`.

Fix `PropsWithBox` types

---

src/components/Checkbox/Checkbox.css.ts
src/components/Checkbox/Checkbox.tsx
src/components/RadioGroup/Item.tsx

If you put the checkbox or radio inside the form it becomes an `input` component and the previous position relative does not work. After this fix, I apply `position:relative` to the label.

Set position relative to label

---

src/components/Popover/Popover.stories.tsx

This PR adds "without arrow" variant in Popover stories.

Improve popover stories

---

src/theme/context.tsx

This fix unblocks SSR for Next.js but we need proper solution for later - it will be tracked in #344

fix: allow SSR

---

src/components/Input/Input.tsx

It fixes TypeScript errors in dashboard:
```
src/products/components/ProductStocks/ProductStocks.tsx:473:22 - error TS2741: Property 'nonce' is missing in type '{ min: number; type: "number"; name: string; disabled: boolean; onChange: (e: ChangeEvent<HTMLInputElement>) => void; value: string | number; size: "small"; placeholder: string; }' but required in type 'Pick<Omit<{ as?: ElementType<any>; children?: ReactNode; className?: string; style?: Record<string, any>; } & { display?: "flex" | "grid" | "none" | "contents" | "block" | { ...; }; ... 86 more ...; flex?: "0" | { ...; }; } & { ...; } & { ...; } & { ...; } & RefAttributes<...>, "translate" | ... 284 more ... | "ente...'.
473                     <Input
~~~~~
```

Fix: input TypeScript types

---

.github/workflows/main.yml
package.json
pnpm-lock.yaml

This PR updates pnpm to version 8 (new lock format and version) and removes not needed `NODE_OPTIONS` env (due to storybook update)

chore: update pnpm to 8 and remove not needed storybook envs

---

.storybook/preview.jsx
src/theme/global.css.ts
src/theme/provider.tsx

This PR applies `colors.background.plain` to body when you are using `ThemeProvider`

fix: apply background color plain to HTML body

---

src/components/BaseInput/BaseInput.css.ts
src/components/Input/Input.stories.tsx
src/components/Input/InputWrapper.tsx

This PR changes `Input` from uncontrolled to controlled. It also removes blue background when user is using Chrome autocomplete.
This PR closes #384

fix: change Input to be controlled

---

.github/workflows/main.yml

I want to merge this change because it changes how `Lint, check types, and test` is run - from now on it will be only executed on pull requests. Previously it was run on push to every branch e.g main.

build: run CI only on PR

---

README.md
src/theme/context.tsx
src/theme/helpers.ts
src/theme/index.ts

This PR adds a helper function that can be used to render CSS variables on the server e.g with Next.js SSR. Usage:
```tsx
import { getCSSVariables } from "@saleor/macaw-ui/next";
import Document, { Head, Html, Main, NextScript } from "next/document";
const css = getCSSVariables("defaultLight"); // or "defaultDark"
export default class AppDocument extends Document {
render() {
return (
<Html style={css}>
<Head />
<body>
<Main />
<NextScript />
</body>
</Html>
);
}
}
```
This PR fixes #344

fix: add helper to render CSS variables on the server

---

src/components/BaseInput/BaseInput.css.ts

I want to merge this change because it applied default variant for `labelRecipe`

fix: apply default label variant

---

src/components/Input/Input.stories.tsx
src/components/Input/Input.tsx

I want to merge this change because it allows passing external handlers (e.g from forms libraries) into the `Input` component.
This PR closes #396

fix: allow passing external handlers to Input

---

src/components/Popover/Content.tsx
src/components/Popover/Popover.css.ts

I want to merge this change because it removes default padding from popover and renders the content as child. This will make it easier to apply custom styling.

fix: render popover content as child

---

src/components/BaseInput/BaseInput.css.ts

I want to merge this change because it disables autocomplete background color coming from 1password.
| ![CleanShot 2023-04-27 at 09 59 31@2x](https://user-images.githubusercontent.com/9116238/234798150-7df1a665-963c-43ad-89b2-16ce22649a23.jpg) | ![CleanShot 2023-04-27 at 09 59 14@2x](https://user-images.githubusercontent.com/9116238/234798096-5f073add-8b0d-46bf-a779-a364b02c6dd7.jpg) |

fix: disable autocomplete color for 1pass

---

src/components/Combobox/Combobox.stories.tsx
src/components/Combobox/Combobox.tsx
src/components/Combobox/ComboboxWrapper.tsx
src/components/Combobox/useComboboxEvents.tsx

I want to merge this change because it makes the `<Combobox/>` component controlled. I also changed the signature of the `onChange` function - now it will return only the selected value not the full `Option` object.

fix: make combobox controlled

---

src/components/Accordion/Accordion.stories.tsx
src/components/Accordion/Item/Content.tsx
src/components/Accordion/Item/Item.tsx
src/components/Accordion/Item/Trigger.tsx
src/components/Accordion/Item/index.ts
src/components/Accordion/index.ts

I want to merge this change because it adds a disabled state and after feedback from developers refactor the Accordion structure. You can see changes in table under:
| `Accordion.Item.Trigger` | `Accordion.Trigger` |
| `Accordion.Item.Content` | `Accordion.Content` |
This PR closes #406

fix: rework accordion structure and add disabled state

---

.github/workflows/main.yml
README.md
src/components/Combobox/Combobox.stories.tsx
src/components/Input/Input.stories.tsx

I want to merge this change because it cleanups controlled input (`Input` & `Combobox`) stories and removes not needed GitHub token from the chromatic workflow.

docs: cleanup controlled stories & remove not needed token

---

src/components/Tooltip/Trigger.tsx

I want to merge this change because it adds a missing ref to the tooltip trigger

fix: add ref to tooltip trigger

---

src/components/Avatar/Avatar.stories.tsx
src/components/Avatar/Store/Store.tsx
src/components/Avatar/User/User.tsx
src/components/Combobox/Combobox.stories.tsx
src/components/Drawer/Content.tsx
src/components/Drawer/Root.tsx
src/components/Drawer/Trigger.tsx
src/components/Dropdown/Content.tsx
src/components/Dropdown/Item.tsx
src/components/Dropdown/Root.tsx
src/components/Dropdown/Trigger.tsx
src/components/Input/Input.stories.tsx
src/components/List/ItemGroup/Content.tsx
src/components/List/ItemGroup/Root.tsx
src/components/List/ItemGroup/Trigger.tsx
src/components/Popover/Anchor.tsx
src/components/Popover/Arrow.tsx
src/components/Popover/Content.tsx
src/components/Popover/Root.tsx
src/components/Popover/Trigger.tsx
src/components/Tooltip/Arrow.tsx
src/components/Tooltip/Content.tsx
src/components/Tooltip/ContentHeading.tsx
src/components/Tooltip/Root.tsx
src/components/Tooltip/Trigger.tsx

I want to merge this change because of it:
1) fixes component naming for storybook snippets
1) adds proper code snippets for `Input` & `Combobox` components

docs: adjust component naming

---

src/components/Combobox/ComboboxWrapper.tsx
src/components/RadioGroup/Group.css.ts
src/components/RadioGroup/Group.tsx
src/components/RadioGroup/RadioGroup.stories.tsx

Add fieldset and label elements to the radio group component. Allow specifying optional `label` prop.

feat(RadioGroup): add fieldset and legend (label)

---

src/theme/Baseline.tsx
src/theme/ThemeProvider.tsx

I want to merge this change because it makes import of external font styles from `rsms.me` optional. It causes CSP errors. 

Make import of external font styles optional

---

src/components/BaseSelect/BaseSelect.css.ts
src/components/Combobox/Combobox.tsx
src/components/Multiselect/Multiselect.stories.tsx
src/components/Multiselect/Multiselect.tsx
src/components/Select/Select.tsx
src/theme/contract.css.ts
src/theme/sprinkles.css.ts
src/theme/themes/common.ts

I want to merge this change because it adds `Portal` to combobox, select and multi select components. It also adds overflow to list of items to select in those components.

fix: add portals to combobox, select & multiselect with overflow

---

src/components/BaseSelect/BaseSelect.css.ts
src/components/Multiselect/Multiselect.tsx
src/components/Popover/Popover.stories.tsx
src/components/Text/Text.stories.tsx

I want to merge this change because it fixes:
* wrong spacing in Multiselect, Combobox and Select component
* wrong gap in Mulitselect
* error when rendering Popover component
* Text story naming
| ![CleanShot 2023-05-30 at 10 42 18@2x](https://github.com/saleor/macaw-ui/assets/9116238/d21e4b1b-a5a4-48d4-8fe8-4f2ec096d08f) | ![CleanShot 2023-05-30 at 10 41 41@2x](https://github.com/saleor/macaw-ui/assets/9116238/927a0682-075f-4009-ab4f-38c538bafd8e) |

fix: adjust components after migrating to the new scale

---

src/components/Multiselect/Multiselect.tsx
src/components/Multiselect/useMultiselectEvents.tsx

I want to merge this change because it shows input in multi-select when no value is found.

fix: muliselect missing input when empty values

---

src/components/BaseSelect/BaseSelect.css.ts
src/components/Combobox/Combobox.stories.tsx
src/components/Combobox/Combobox.tsx
src/components/Multiselect/Multiselect.stories.tsx
src/components/Multiselect/Multiselect.tsx
src/components/Select/Select.stories.tsx
src/components/Select/Select.tsx

I want to merge this change because it fixes two issues:
* list of items to select taking space on the UI
* broken UI when there is a helper text
| ![CleanShot 2023-06-02 at 14 36 07@2x](https://github.com/saleor/macaw-ui/assets/9116238/674b7ab6-561a-442f-95e7-8ca0d6cfbd68) | ![CleanShot 2023-06-02 at 14 35 46@2x](https://github.com/saleor/macaw-ui/assets/9116238/b464c55e-0d76-4bce-804d-f401ff1172de) |

fix: bring back position absolute for select list

---

src/components/Checkbox/Checkbox.css.ts
src/components/Checkbox/Checkbox.tsx

I want to merge this change because it fixes shrinking checkbox when used in some flexboxes.
It also no longer exposes radix api, checkbox props are explicit and `...props` is applied to the wrapper.

fix: checkbox types and shrinking

---

src/components/Select/Select.tsx
src/components/Select/SelectWrapper.tsx

I want to merge this change because it fixes a regression from #459 
| ![CleanShot 2023-06-27 at 14 58 46@2x](https://github.com/saleor/macaw-ui/assets/9116238/46d559d7-b4a6-42db-b49c-9678d8542b6e) | ![CleanShot 2023-06-27 at 14 58 02@2x](https://github.com/saleor/macaw-ui/assets/9116238/a1b2475c-58ba-4559-9770-bffb05ede5bf) |

fix: select regression

---

package.json

I want to merge this change because this PR fixes errors from https://publint.dev/@saleor/macaw-ui@0.8.0-pre.101

fix: package json fields used by package directory

---

.storybook/main.ts
src/components/Box/Box.tsx
src/components/List/List.tsx

I want to merge this change because it allows spreading component props on its component if there is a ref defined e.g:
```tsx
const props: ListProps = {};
<List {...props} />
```

fix: wrong props with box type

---

src/components/ExperimentalFilters/index.ts
src/components/ExperimentalFilters/useEvents.tsx

I want to merge this change because it exports `FilterEvent` type from experimental filters.

feat: export FilterEvent for experimental filters

---

src/components/BaseSelect/types.ts
src/components/Combobox/Common/useCombobox.tsx
src/components/Combobox/Dynamic/DynamicCombobox.tsx
src/components/Combobox/Static/Combobox.tsx
src/components/Multiselect/Common/useMultiselect.tsx
src/components/Multiselect/Dynamic/DynamicMultiselect.tsx
src/components/Multiselect/Static/Multiselect.tsx
src/components/Select/Select.stories.tsx
src/components/Select/Select.tsx
src/components/Select/useSelect.tsx

I want to merge this change because is the ability to pass additional fields to select/combobox/multiselect options.
For example, after this PR is closed it will be possible to:
```tsx
<Select
// value inferred from options - in this case { label: string, value: string, slug: string }
value={null}
options={[{ label: "", value: "", slug: "" }]}
// newValue inferred from options - in this case { label: string, value: string, slug: string }
onChange={(newValue) => {}}
/>
);
```

feat: allow passing generic options to selects

---

package.json
tsconfig.json

I want to merge this change because it fixes npm bundle errors for `/next` package
This PR closes #489 
After this PR is merged:

fix: exported types for npm

---

src/components/ExperimentalFilters/ExperimentalFilters.stories.tsx
src/components/ExperimentalFilters/Row.tsx
src/components/ExperimentalFilters/index.ts

I want to merge this change because it adjusts the width of the condition selected in the experimental row. I also added export for loading skeleton.
| ![CleanShot 2023-07-12 at 17 03 55@2x](https://github.com/saleor/macaw-ui/assets/9116238/3184e98d-5d3b-4f81-8675-6b9358358737)| ![CleanShot 2023-07-13 at 09 14 01@2x](https://github.com/saleor/macaw-ui/assets/9116238/bb4e10a6-cdd1-49fa-b594-2244be5ab948) |

feat: change width of exp filter row export loading skeleton

---

src/components/BaseInput/BaseInput.css.ts
src/components/BaseInput/HelperText.tsx
src/components/ExperimentalFilters/EventEmitter.ts
src/components/ExperimentalFilters/ExperimentalFilters.stories.tsx
src/components/ExperimentalFilters/Filters.tsx
src/components/ExperimentalFilters/RightOperator.tsx
src/components/ExperimentalFilters/Root.tsx
src/components/ExperimentalFilters/Row.tsx
src/components/ExperimentalFilters/constrains.ts
src/components/ExperimentalFilters/index.ts
src/components/ExperimentalFilters/types.ts
src/components/ExperimentalFilters/useEvents.tsx
src/components/ExperimentalFilters/utils.ts

I want to merge this change because it adds error state and constrains to Experimental filters. I also did a bit of cleanup.

feat: experimental filters - add error state and constrains

---

src/components/ExperimentalFilters/ExperimentalFilters.stories.tsx
src/components/ExperimentalFilters/Filters.tsx
src/components/ExperimentalFilters/RightOperator.tsx
src/components/ExperimentalFilters/Root.tsx
src/components/ExperimentalFilters/Row.tsx
src/components/ExperimentalFilters/errors.ts
src/components/Select/Select.tsx

I want to merge this change because it adds support for an array of errors inside Filters and ranges for date & datetime.

feat: add multiple errors support and date/datetime ranges to experimental filters

---

src/components/Popover/Content.tsx

I want to merge this change because it adds outside click/focus interaction to Popover.
It is based on Radix [`onInteractOutside`](https://www.radix-ui.com/docs/primitives/components/popover#content)

feat: add handler for interaction outside popover

---

src/components/Popover/Arrow.tsx
src/components/Popover/Popover.stories.tsx
src/theme/sprinkles.css.ts

I want to merge this change because it changes a bit API on `Popover.Arrow`:
| `<Arrow backgroundColor={vars.colors.background.subdued} />` | `<Arrow fill="subdued" />` |

fix: use sprinkles in popover arrow

---

src/components/Modal/Modal.stories.tsx
src/components/Modal/Root.tsx

I want to merge this change because it allows Modal component to be controlled.

feat: controlled modal

---

src/components/Select/useSelect.tsx

I want to merge this change because select did not work with empty string as default value
This PR closes #539

fix: select not working with empty string

---

src/components/BaseSelect/types.ts
src/components/Combobox/Common/useCombobox.tsx
src/components/Combobox/Dynamic/DynamicCombobox.stories.tsx
src/components/Combobox/Dynamic/DynamicCombobox.tsx
src/components/Combobox/Static/Combobox.tsx
src/components/Combobox/Static/StaticCombobox.stories.tsx
src/components/ExperimentalFilters/RightOperator.tsx
src/components/ExperimentalFilters/Row.tsx

I want to merge this change because it fixes the selected option when the user clear input and adds adornment to allow create swatch component.

feat: add adornments to combobox

---

README.md

I want to merge this change because instruction to install dependencies in legacy for running push hook properly is missing.

feat: add instruction to install dependencies in legacy to readme

---

src/components/Multiselect/Common/useMultiselect.tsx

fix: wrong value pass to onInputValueChange in useMultiselect

---

src/theme/sprinkles.css.ts

I want to merge this change because it adds list style

feat: add list style

---

src/hooks/useFloating.ts

I want to merge this change because it fixes an issue when we use Select, Combobox, Multiselect inside Modal components. The problem causes Modal through set pointer-event none to body element when open. The Portal used for dropdown doesn't have a set pointer event so it inherits it from body and that causes problem with select item in dropdown.

fix: dropdown block pointer events when used inside modal

---

src/theme/sprinkles.css.ts

I want to merge this change because we need `justify-self` for various advanced grid-flexbox mixed layouts, right now specifically https://github.com/saleor/saleor-dashboard/issues/4219

feat: add justify-self to sprinkles

---

src/components/Modal/Content.tsx
src/components/Modal/Modal.stories.tsx

I want to merge this change because it fix a problem that I can't scroll combobox dropdown inside modal.
According to Radix docs to be able to scroll we have to wrap Dialog.Content inside Dialog.Overlay
https://www.radix-ui.com/primitives/docs/components/dialog#scrollable-overlay

fix: scroll inside modal content

---

src/components/Multiselect/Common/MultiselectWrapper.tsx
src/components/Multiselect/Dynamic/DynamicMultiselect.stories.tsx
src/components/Multiselect/Dynamic/DynamicMultiselect.tsx
src/components/Multiselect/Static/Multiselect.stories.tsx
src/components/Multiselect/Static/Multiselect.tsx
src/components/Select/Select.stories.tsx
src/theme/themes/defaultLight.ts

I want to merge this change because it fixes multiselect (static & dynamic) height.
| ![CleanShot 2023-12-20 at 12 53 52@2x](https://github.com/saleor/macaw-ui/assets/9116238/ab4d5604-0060-4dd9-8bf7-05a8028ecb3c) | ![CleanShot 2023-12-20 at 12 53 03@2x](https://github.com/saleor/macaw-ui/assets/9116238/0cd7a078-e75a-472f-8a72-45b7734288aa) |

fix: multiselect height

---

src/components/BaseSelect/BaseSelect.css.ts
src/components/BaseSelect/NoOptions.tsx
src/components/BaseSelect/helpers.ts
src/components/BaseSelect/index.ts
src/components/Combobox/Dynamic/DynamicCombobox.stories.tsx
src/components/Combobox/Dynamic/DynamicCombobox.tsx
src/components/Combobox/Static/Combobox.tsx
src/components/Combobox/Static/StaticCombobox.stories.tsx
src/components/Multiselect/Common/useMultiselect.tsx
src/components/Multiselect/Dynamic/DynamicMultiselect.stories.tsx
src/components/Multiselect/Dynamic/DynamicMultiselect.tsx
src/components/Multiselect/Static/Multiselect.stories.tsx
src/components/Multiselect/Static/Multiselect.tsx
src/components/Select/Select.stories.tsx
src/components/Select/Select.tsx
src/theme/sprinkles.css.ts

I want to merge this change because it allows displaying text inside the dropdown when there are no options to show to give use clear feedback.
It applies to all selects, multiselects and comboboxes.

feat: show empty text

---

.storybook/components/BorderRadius.tsx
.storybook/components/Shadow.tsx
.storybook/components/Spacings.tsx

I want to merge this change because it fixes wrong color names while used with storybook tokens section.

docs: fix storybook tokens section

---

src/components/Combobox/Common/useCombobox.tsx
src/components/Combobox/Dynamic/DynamicCombobox.tsx
src/components/Combobox/Static/Combobox.tsx
src/components/Multiselect/Common/useMultiselect.tsx
src/components/Select/Select.tsx
src/components/Select/useSelect.tsx

I want to merge this change because it fixes case when user passes `string` as value to `Select`, `Combobox` and `Multiselect` - now it should return `string` onChange.

fix: pass string onChange when value is string for selects

---

src/components/BaseSelect/helpers.ts
src/components/Combobox/Dynamic/DynamicCombobox.tsx
src/components/Combobox/Static/Combobox.tsx
src/components/Multiselect/Dynamic/DynamicMultiselect.tsx
src/components/Select/Select.tsx

I want to merge this change because its fixes disabled state on combobox, select and multiselect. 
Also fix disabled label color in select component.

fix: open select,combobox, multiselect when disabled

---

.github/workflows/chromatic.yml
.github/workflows/stale-bot.yml
package.json

I want to merge this change because it fixes:
* Wrong name for publish script in pkg.json
* Stalebot closing rfc issues
* Name for stalebot workflow (to be consistent with other filenames in repo)
* Chromatic branch name

Fix: missing script, stale bot rfc closing, chromatic branch name

---

.changeset/few-countries-hope.md
.github/workflows/dev-release.yml
.github/workflows/prepare-release.yml
package.json

I want to merge this change because it adds ability to release macaw-ui as dev tag if you add label on PR.

Add ability to release dev tag

---

.changeset/lemon-tools-tan.md
src/components/Button/Button.css.ts
src/theme/themes/common.ts

I want to merge this change because it:
- fixes default button font weight (should be bold)
- changes bold font weight to 600

Fix button font weights

---

.changeset/fuzzy-brooms-travel.md
src/components/Combobox/Dynamic/DynamicCombobox.tsx
src/components/Combobox/Static/Combobox.tsx

I want to merge this change because it adds a `data-portal-for={id}` to combobox dropdown list box.

Pass `data-portal-for` attr to list in portal

---

src/components/BaseSelect/types.ts
src/components/Combobox/Dynamic/DynamicCombobox.tsx
src/components/Combobox/Static/Combobox.tsx
src/components/Combobox/Static/StaticCombobox.stories.tsx
src/components/Multiselect/Dynamic/DynamicMultiselect.tsx
src/components/Multiselect/Static/Multiselect.stories.tsx
src/components/Multiselect/Static/Multiselect.tsx
src/components/Select/Select.stories.tsx
src/components/Select/Select.tsx

Handle disable option in Select, Combobox and Multiselect

---

.changeset/flat-avocados-build.md
src/components/Skeleton/Skeleton.tsx

I want to merge this change because it improves how UI looks during loading. Skeleton now has similar height to text

Change default `Skeleton` height

---

.changeset/loud-tools-poke.md
src/components/BaseSelect/useHighlightedIndex.ts
src/components/Combobox/Common/useCombobox.tsx

Refactor calculating highlight index logic for Combobox and Select

---

README.md

I want to merge this change because it fixes broken link to Chrome Extension in README

Fix Chrome Extension link in README

---

.changeset/metal-jars-try.md
src/components/Icons/SVGWrapper/SVGWrapper.tsx
src/components/Multiselect/Common/Adornment.tsx

I want to merge this change because it fixes an issue where we would need to use `@ts-expect-error` or `@ts-ignore` for icons from macaw when we needed custom overrides (e.g. styles, tabIndex, etc.).
It simply allows passing all SVG element props, like so:
```ts
<GripIcon tabIndex={0} className={className} style={{ cursor: "grip" }} />
```

Allow all SVG properties for icons

---

.changeset/hungry-frogs-tie.md
src/components/Accordion/common.css.ts

I want to merge this change because it fixes Accordion overflow issue by setting `overflow: visible` on open content to ensure content displays correctly.

Fix accordion overflow
